In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [ ]:
import warnings
warnings.filterwarnings('ignore')

In [ ]:
df = pd.read_csv('pulsar_stars.csv')

In [ ]:
df.shape

(17898, 9)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17898 entries, 0 to 17897
Data columns (total 9 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0    Mean of the integrated profile                17898 non-null  float64
 1    Standard deviation of the integrated profile  17898 non-null  float64
 2    Excess kurtosis of the integrated profile     17898 non-null  float64
 3    Skewness of the integrated profile            17898 non-null  float64
 4    Mean of the DM-SNR curve                      17898 non-null  float64
 5    Standard deviation of the DM-SNR curve        17898 non-null  float64
 6    Excess kurtosis of the DM-SNR curve           17898 non-null  float64
 7    Skewness of the DM-SNR curve                  17898 non-null  float64
 8   target_class                                   17898 non-null  int64
dtypes: float64(8), int64(1)
memory usage: 1.2 MB

In [ ]:
df.head()

    Mean of the integrated profile  ...  target_class
0                       140.562500  ...             0
1                       102.507812  ...             0
2                       103.015625  ...             0
3                       136.750000  ...             0
4                        88.726562  ...             0

[5 rows x 9 columns]

In [ ]:
df.columns = ['IP Mean', 'IP Sd', 'IP Kurtosis', 'IP Skewness', 'DM-SNR Mean', 'DM-SNR Sd', 'DM-SNR Kurtosis', 'DM-SNR Skewness', 'target_class']

In [ ]:
df['target_class'].value_counts()

target_class
0    16259
1     1639
Name: count, dtype: int64

In [ ]:
df['target_class'].value_counts(normalize=True)

target_class
0    0.908426
1    0.091574
Name: proportion, dtype: float64

In [ ]:
df.isnull().sum()

IP Mean            0
IP Sd              0
IP Kurtosis        0
IP Skewness        0
DM-SNR Mean        0
DM-SNR Sd          0
DM-SNR Kurtosis    0
DM-SNR Skewness    0
target_class       0
dtype: int64

In [ ]:
y = df['target_class']
X = df.drop('target_class', axis=1)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0, shuffle=True)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
from sklearn.svm import SVC
svm_classifier = SVC(kernel='linear', C=1.0, class_weight='balanced')
svm_classifier.fit(X_train, y_train)

SVC(class_weight='balanced', kernel='linear')

In [ ]:
from sklearn.metrics import accuracy_score , confusion_matrix , classification_report
y_pred =svm_classifier.predict(X_test)

In [ ]:
accurecy = accuracy_score(y_test, y_pred)
print('Accuracy score: {0:0.4f}'.format(accuracy_score(y_test, y_pred)))

Accuracy score: 0.9757

In [ ]:
classification_accurecy = classification_report(y_test, y_pred)
print(classification_accurecy)

              precision    recall  f1-score   support

           0       0.99      0.98      0.99      3306
           1       0.80      0.92      0.85       274

    accuracy                           0.98      3580
   macro avg       0.89      0.95      0.92      3580
weighted avg       0.98      0.98      0.98      3580

In [ ]:
con_matrix = confusion_matrix(y_test, y_pred)
print(con_matrix)

[[3242   64]
 [  23  251]]